
# This is CI trigger for the Intel Redhat DCI-Apps Job
# It requires a user name and a PAT to access the private repo that contains the actual action.
# It will trigger on a pull request - can also be run manually

name: dci-apps- workflow-trigger
on: [workflow_dispatch, pull_request]

jobs:
  using-trigger-and-wait:
    name: Remote Trigger for DCI Apps Job
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
         owner: intel
         repo:  ocpeng
         github_user: intelocpeng
         github_token: ${ {secrets.OCP_ENG} }
         workflow_file_name: dci-app-agent-workflow.yml
         ref: main
         wait_interval: 10
         propagate_failure: true
         trigger_workflow: true
         wait_workflow: true

